services:
  web:
    container_name: "rss_dev_newsletter"
    build:
      dockerfile: Dockerfile

    restart: always

    networks:
      - postgres

    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8080/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

    environment:
      - TZ=Europe/Paris
      - APP__AI__MISTRAL__API_KEY=${APP__AI__MISTRAL__API_KEY}
      - APP__DATABASE__HOST=${APP__DATABASE__HOST}
      - APP__DATABASE__PORT=${APP__DATABASE__PORT}
      - APP__DATABASE__USER=${APP__DATABASE__USER}
      - APP__DATABASE__PASSWORD=${APP__DATABASE__PASSWORD}
      - APP__DATABASE__DATABASE=${APP__DATABASE__DATABASE}

    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  postgres:
    external: true