[server]
port = 8080

[ai]
enable = true
cron_string="0 30 21 * * *"

[ai.gemini]
api_key= ""
model = "models/gemini-2.5-pro"

[ai.mistral]
api_key = ""
endpoint = "https://api.mistral.ai/v1"
max_retries = 5
timeout = 120
model = "mistral-small-latest"
classification_agent_id=""
summary_agent_id=""

[notification]
enable = true
cron_string="0 45 21 * * *"

[database]

host = ""
port = ""
user = ""
password = ""
database = ""

[rss]
enable = true
cron_string="*/30 * * * * *"