mode = "dev"

[tldr_settings]
mark_email_as_read = false

[git_settings]
enable = false
branch = "main"

[storage_settings]
repository_path = "tldr_newsletter_storage"

[ai_settings]
api_key= ""
model = "models/gemini-2.5-pro"
system_prompt_path = "ai_system_prompt.txt"
user_prompt_path = "ai_user_message.txt"