mode = "dev"

[tldr]
mark_email_as_read = false

[git]
enable = false
branch = "main"

[storage]
repository_path = "tldr_newsletter_storage"

[ai]
enable = true
api_key= ""
url = ""
model = "models/gemini-2.5-pro"
article_resume_system_prompt_path = "ai_article_resume_system_prompt.txt"
global_resume_system_prompt_path = ""
user_prompt_path = "ai_user_message.txt"


[notification]

[notification.discord]
enable = true
webhook_url = ""